# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'huidu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for huidu

  target 'huiduTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDWebImage'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'FMDB'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SVProgressHUD'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'WMPageController'
  pod 'ZFPlayer'
  pod 'BAButton'

  target 'huiduUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
